# SIWA Lab 2 - Wprowadzenie  do torcha

In [ ]:
import numpy as np
import torch
import time

### 1. Tworzymy tensory

1.1 Tworzymy  tensor bezpośrednio z danych.

In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

1.2 Tworzymy tensor z numpy array

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

1.3 Tworzymy tensor z samymi jedynkami o takim samym rozmiarze, co X.

In [ ]:
x_ones = torch.ones_like(x_np)
x_ones

tensor([[1, 1],
        [1, 1]])

1.4. Tworzymy tensor z wartościami z rozkładu normalnego.

In [ ]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.3428, 0.6082],
        [0.3829, 0.8221]])

### 2. Atrybuty tensora

2.1 Wymiary tensora

In [ ]:
tensor = torch.rand(3,4)
tensor.shape

torch.Size([3, 4])

2.2 Typ wartości w tensorze

In [ ]:
tensor.dtype

torch.float32

2.3 Czy tensor jest przechowywany na CPU czy na GPU

In [ ]:
tensor.device

device(type='cpu')

### 3. Operacje na tensorach

3.1 Indeksowanie i slice

In [ ]:
tensor = torch.rand(4, 4)
print(f"Pierwszy wiersz: {tensor[0]}")
print(f"Pierwsza kolumna: {tensor[:, 0]}")
print(f"Ostatnia kolumna: {tensor[..., -1]}")
tensor[:,1] = 0 # Wypełnij kolumnę zerami
print(tensor)

Pierwszy wiersz: tensor([0.8846, 0.4597, 0.1991, 0.0404])
Pierwsza kolumna: tensor([0.8846, 0.8623, 0.7295, 0.4655])
Ostatnia kolumna: tensor([0.0404, 0.7309, 0.2564, 0.6018])
tensor([[0.8846, 0.0000, 0.1991, 0.0404],
        [0.8623, 0.0000, 0.1286, 0.7309],
        [0.7295, 0.0000, 0.8501, 0.2564],
        [0.4655, 0.0000, 0.5436, 0.6018]])


3.2 Łączenie tensorów wzdłuż wybranego wymiaru

In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.8846, 0.0000, 0.1991, 0.0404, 0.8846, 0.0000, 0.1991, 0.0404, 0.8846,
         0.0000, 0.1991, 0.0404],
        [0.8623, 0.0000, 0.1286, 0.7309, 0.8623, 0.0000, 0.1286, 0.7309, 0.8623,
         0.0000, 0.1286, 0.7309],
        [0.7295, 0.0000, 0.8501, 0.2564, 0.7295, 0.0000, 0.8501, 0.2564, 0.7295,
         0.0000, 0.8501, 0.2564],
        [0.4655, 0.0000, 0.5436, 0.6018, 0.4655, 0.0000, 0.5436, 0.6018, 0.4655,
         0.0000, 0.5436, 0.6018]])


3.3 Mnożenie macierzy. y1, y2, y3 dadzą ten sam wynik.

In [ ]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[0.8238, 0.8179, 0.8249, 0.5444],
        [0.8179, 1.2943, 0.9257, 0.9111],
        [0.8249, 0.9257, 1.3205, 0.9560],
        [0.5444, 0.9111, 0.9560, 0.8744]])

3.4 Mnożenie element razy element. z1, z2, z3 dadzą ten sam wynik

In [ ]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)


tensor([[0.7825, 0.0000, 0.0396, 0.0016],
        [0.7436, 0.0000, 0.0165, 0.5342],
        [0.5321, 0.0000, 0.7227, 0.0657],
        [0.2167, 0.0000, 0.2955, 0.3621]])

4. Zamiana torch i numpy

In [ ]:
t = torch.ones(5)

n = t.numpy()

In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

### 5. Zmiana wymiarów tensora

In [ ]:
t = torch.rand((5, 2))
t.reshape(-1)

tensor([0.4679, 0.0961, 0.0285, 0.9166, 0.9829, 0.6856, 0.3040, 0.9065, 0.7905,
        0.9334])

## Zadania

### Zadanie 1
Stwórz 4 tensory:

$A$ : macierz jedynek 4x7

$B$ : macierz o takim samym wymiarze co A, ale wartości macierzy mają pochodzić z rozkładu normalnego

$C$ : wektor z liczbami parzystymi od 2 do 20 włącznie

$D$ : tensor utworzony na podstawie numpy array Z

In [ ]:
Z = np.vander([1, 2, 3, 5], 4)
Z

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [ ]:
A = np.ones((4, 7))
B = np.random.normal(size=(4, 7))
C = np.arange(2, 21, 2)
D = np.array(Z)

### Zadanie 2
Przemnóż macierz B przez C, a następnie dodaj macierz D.
$$D = A \cdot B + C$$

In [ ]:
A = torch.tensor([[2, 4], [5, 7]])
B = torch.tensor([[1, 1], [2, 3]])
C = torch.tensor([[10, 10], [12, 1]])

D = torch.matmul(A, B) + C

### Zadanie 3

Przemnóż sumę kolumn macierzy A przez sumę wszystkich elementów macierzy B (skalar).
$$A = \begin{bmatrix}
1 & 2 \\
1 & 1
\end{bmatrix} \
B = \begin{bmatrix}
1 & 2 & 3\\
3 & 2 & 1
\end{bmatrix} \
\ \ C = \begin{bmatrix}
2 & 3\\
\end{bmatrix} \cdot 12 =
\begin{bmatrix}
24 & 36 \\
\end{bmatrix}$$

In [ ]:
A = torch.tensor([[1, 2], [1, 1]])
B = torch.tensor([[1, 2, 3], [3, 2, 1]])

C = torch.sum(A, dim=0) * torch.sum(B)
C

tensor([24, 36])

### Zadanie 4
Przekształć macierz A tak, żeby drugą kolumnę stanowiła spłaszczona macierz A, a pierwszą kolumnę indeks danego wiersza.

$$A = \begin{bmatrix}
5 & -2 \\
10 & 41
\end{bmatrix}
$$

$$B = \begin{bmatrix}
0 & 5 \\
1 & -2 \\
2 & 10 \\
3 & 41 \\
\end{bmatrix}
$$


In [ ]:
A = torch.tensor([[5, -2], [10, 41]])

B = torch.flatten(A)
B

tensor([ 5, -2, 10, 41])

In [ ]:
A1 = torch.flatten(A[:, :1])
A2 = torch.flatten(A[:, 1:2])
B = torch.stack((A2, A1), dim=1)
B

tensor([[-2,  5],
        [41, 10]])

### Zadanie 5
O ile szybsze są obliczenia na GPU od CPU?
Policz czas obliczeń na CPU i GPU.

In [ ]:
device = 'cpu'

start_time = time.time()

X = torch.rand(2, 2).to(device)
Y = torch.rand_like(X).to(device)

Z = 2*torch.ones(2, 2).to(device)

A = X * Y
B = Y @ Z
C = A + B

cpu_time = time.time() - start_time
print("Czas obliczeń na CPU:", cpu_time)

Czas obliczeń na CPU: 0.0027892589569091797


In [ ]:
device = 'cuda'

start_time = time.time()

X = torch.rand(2, 2).to(device)
Y = torch.rand_like(X).to(device)

Z = 2*torch.ones(2, 2).to(device)

A = X * Y
B = Y @ Z
C = A + B

gpu_time = time.time() - start_time
print("Czas obliczeń na GPU:", gpu_time)

In [ ]:
print("Przyspieszenie GPU w porównaniu z CPU:", cpu_time / gpu_time, "razy")